---
name: ((deployment_name))

releases:
- name: "concourse"
  version: "3.14.1"
  url: "https://bosh.io/d/github.com/concourse/concourse?v=3.14.1"
  sha1: "6be91b70ecc7ce233d2aff5d03ed28c8eab3d132"
- name: "garden-runc"
  version: "1.15.1"
  url: "https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.15.1"
  sha1: "bdac2dc7debc2e9b4b9e32f009cb93ac281e5480"
- name: "postgres"
  version: "28"
  url: "https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=28"
  sha1: "c1fcec62cb9d2e95e3b191e3c91d238e2b9d23fa"

instance_groups:
- name: concourse
  instances: 1
  azs: [((az))]
  networks:
  - name: ((network_name))
  azs: [((az))]
  persistent_disk: 10240
  vm_type: ((vm_type))
  stemcell: trusty
  jobs:
  - release: concourse
    name: atc
    properties:
      log_level: debug
      postgresql:
        database: atc
        role:
          name: atc
          password: ((postgres_password))

      main_team:
        auth:
          allow_all_users: true
      basic_auth_username: admin
      basic_auth_password: ((admin_password))

      add_local_users:
      - test:$2a$10$sDB6AsH2HheOWHILrnHVJOCZq/GYtUYE02ypJJTQBmWJNivYNhP3y

      token_signing_key: ((token_signing_key))

  - release: concourse
    name: tsa
    properties:
      log_level: debug
      host_key: ((tsa_host_key))
      token_signing_key: ((token_signing_key))
      authorized_keys: [((worker_key.public_key))]

  - release: postgres
    name: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: atc
        roles:
        - name: atc
          password: ((postgres_password))

  - release: concourse
    name: worker
    properties:
      drain_timeout: 10m
      tsa: {worker_key: ((worker_key))}
      log_level: debug

  - release: concourse
    name: baggageclaim
    properties:
      log_level: debug

  - release: garden-runc
    name: garden
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        allow_host_access: true

variables:
- name: postgres_password
  type: password
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh
- name: admin_password
  type: password

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
